//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnileverDMSDistributorDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleRevenue
    {
        public int ID { get; set; }
        public int SaleManId { get; set; }
        public int ProId { get; set; }
        public Nullable<int> SoldQuantity { get; set; }
        public Nullable<int> TotalCash { get; set; }
        public Nullable<System.DateTime> StatisDate { get; set; }
    }
}
