//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnileverDMSDistributorDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UnileverDMS_DistributorsEntities : DbContext
    {
        public UnileverDMS_DistributorsEntities()
            : base("name=UnileverDMS_DistributorsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<DefferredLiability> DefferredLiabilities { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<SaleArea> SaleAreas { get; set; }
        public virtual DbSet<SaleMan> SaleMans { get; set; }
        public virtual DbSet<SaleRevenue> SaleRevenues { get; set; }
    }
}
