//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnileverDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefferredLiability
    {
        public int ID { get; set; }
        public int OrderID { get; set; }
        public Nullable<System.DateTime> DebtDate { get; set; }
        public Nullable<int> PeriodOfDebt { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
