//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnileverDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterestRate
    {
        public int ID { get; set; }
        public Nullable<int> OutOfPeriod { get; set; }
        public Nullable<double> InterestPayable { get; set; }
    }
}
