//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnileverDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int ID { get; set; }
        public Nullable<int> DistributorID { get; set; }
        public int ProID { get; set; }
        public Nullable<int> OrderedQuantity { get; set; }
        public Nullable<int> SoldQuantity { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
    }
}
